### ISSUE TITLE
fixed width

### ISSUE THREAD

**Issue by TheAsphyX** [softsimon/angular-2-dropdown-multiselect#122]
Hi,
i'm unable to full span width with bootstrap 4 and input-group-addon, btn-block class only works for BS3 ...
i'm doing something wrong ?
Thank you.

**Comment by chris--jones** [comment]
Can you give some sample code?
You can always create your own class and assign it to the buttonClasses in config.

`btn-block` from BS3 is basically just
```css
.btn-block {
    display: block;
    width: 100%;
}
````
