### ISSUE TITLE
Add option to set svg icons for checked styles.

### ISSUE THREAD

**Issue by dietergeerts** [softsimon/angular-2-dropdown-multiselect#136]
There are now three options, but both fontawesome and glyphicons are font based. We use svg icons in our application, so it would be great if we could set these options, probably not the svg file alone, but also a wrapper class.

**Comment by chris--jones** [comment]
You could work around this by styling the checkboxes with css, I'll throw an example together later.

**Comment by chris--jones** [comment]
Example using the material icons for unchecked and checked boxes, with an animation for fun.
[ic_check_box_outline_blank_black_24px.svg](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_check_box_outline_blank_black_24px.svg)
[ic_check_box_black_24px.svg](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_check_box_black_24px.svg)

```css
.dropdown-menu > li.dropdown-item > a {
  padding-left:38px;
}
.dropdown input[type=checkbox] {
  position:absolute;
  width:0;
  height:0;
}
.dropdown input[type=checkbox]:before, .dropdown input[type=checkbox]:checked:after {
  content:'';
  display:block;
  position:absolute;
  height:24px;
  width:24px;
  left:-28px;
}
.dropdown input[type=checkbox]:before {
  background-image:url('/images/ic_check_box_outline_blank_black_24px.svg');
}
.dropdown input[type=checkbox]:checked:after {
  animation:scaleFade 0.2s cubic-bezier(0.46, 0.03, 0.52, 0.96) alternate;
  background-image:url('/images/ic_check_box_black_24px.svg');
}
@keyframes scaleFade {
  0% { transform:scale(0.6); opacity:0 }
  80% { transform:scale(1.4); opacity:0.8 }
  100% { transform:scale(1); opacity:1 }
}
```
