### ISSUE TITLE
Question-Overwrite default styling

### ISSUE THREAD

**Issue by minhtam-nguyennhat** [softsimon/angular-2-dropdown-multiselect#46]
Hi,

Just wondering if there is a way to overwrite the default styling. Specifically the  .dropdown-menu class ?

Thanks
Tam

**Comment by chris--jones** [comment]
The only configuration options for styling I'm aware of are:
- checkedStyle
- buttonClasses
- itemClasses

You can always override the dropdown-menu class yourself with css rules:
e.g.
```css
ss-multiselect-control ul.dropdown-menu {
    background-color: #aceab0;
    font-variant: small-caps;
    font-size: 1.5em;
}
```

I think the styling requires a bit of an overhaul, particularly to support something like #49, but I'll raise a separate item for this
